singleuser:
  image:
    name: "quay.io/jupyter/all-spark-notebook"
    tag: "latest"

  extraEnv:
    MLFLOW_TRACKING_URI: "http://mlflow.default.svc.cluster.local:5000"
    MLFLOW_S3_ENDPOINT_URL: "http://minio.default.svc.cluster.local:9000"
    AWS_ENDPOINT: "http://minio.default.svc.cluster.local:9000"
    AWS_ACCESS_KEY_ID: "rootuser"
    AWS_SECRET_ACCESS_KEY: "rootpass123"
    AWS_REGION: "eu-west-1"
    AWS_ALLOW_HTTP: "true"
    AWS_S3_ALLOW_UNSAFE_RENAME: "true"

proxy:
  service:
    type: LoadBalancer
